--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JinodkDevTeam/FI-Utils
build-by-default: true
branches:
- main
projects:
  FI-Utils:
    model: virion
    type: library
    path: FI-Utils
...
